name: Conventional commit check

on:
  push:
    branches:
      - master

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
        id: releascog
        with:
          release: true
          git-user: "Cog Bot"
          git-user-email: "cogbot@indraft.blog"
          check-latest-tag-only: true

      # The version number is accessible as a github action output
      - name: Print version
        run: "echo '${{ steps.release.outputs.version }}'"
