name: eslint

on:
  pull_request:
    paths:
      - "**/components/**"
      - "**/screens/**"
      - "**/utils/**"
      - "**/App.js"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: npm run lint
